apiVersion: apps/v1
kind: Deployment
metadata:
  name: flint-gcbm
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flint-gcbm
  template:
    metadata:
      labels:
        app: flint-gcbm
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: flint-gcbm
          image: mojaglobal.azurecr.io/moja-global/rest_api_flint_gcbm:master
          ports:
            - containerPort: 8080
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 125Mi
            limits:
              cpu: 256m
              memory: 200Mi
      imagePullSecrets:
      - name: acr-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: flint-gcbm
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      name: port8080
      port: 8080
      protocol: TCP
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: flint-gcbm
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flint-gcbm
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flint-gcbm
            port:
              number: 8080
