name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]

jobs:
  linting-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Upgrade pip version
        run: |
          python3 -m pip install --upgrade pip
      - name: Lint source with Flake8
        run: |
          pip3 install flake8
          flake8 .

  linting-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: "./local/rest_api_flint.example/Dockerfile
            ./local/rest_api_gcbm/Dockerfile
            ./local/rest_api_gcbm/Dockerfile.base
            ./local/rest_api_gcbm/Dockerfile.flint
            ./local/rest_api_gcbm/Dockerfile.gcbm
            ./layered/cloud-run/Dockerfile
            ./layered/compute-engine/Dockerfile
            ./layered/ingress/Dockerfile"
          error_level: 0
          output_format: tty

  linting-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main
