name: Test FLINT.Cloud

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test-rest-api-flint-example:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./local/rest_api_flint.example/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build REST API FLINT Example
        # Docker image is created and run in detached mode at port 8080
        run: |
          docker build . --file Dockerfile --tag rest_api_flint.example
          docker run --rm -d -p 8080:8080 rest_api_flint.example:latest
        
      - name: Test endpoints
        run: |
          cd ../
          pip install -U pytest
          pytest tests -v

      - name: Peform container scan for vulnerabilities
        uses: azure/container-scan@v0
        with:
          image-name: rest_api_flint.example
